<?php

namespace App\Traits;

trait HmpkErrors {

    public function errorRef($code) {
        $refs = array(
            '0' => "SUCCESS",
            '1' => "USERNOTFOUND",
            '2' => "INVALIDUSERID",
            '3' => "REQUIREDPARAMETERSMISSING",
            '4' => "REQUIREDPARAMETERCONTAINDATAFORMATERROR",
            '5' => "REQUIREDPARAMTERSCONTAONNODATA",
            '6' => "INTERNALSOFTWAREEXCEPTION",
            '7' => "DATABASEEXCEPTION",
            '8' => "INVALIDMESSAGEFORMAT",
            '9' => "UNSUPPORTEDCOMMAND",
            '10' => "OPTIMITICLOCKINGERROR",
            '11' => "TOMANYPAYLOADS",
            '12' => "TIMESTAMPMALFORMED",
            '13' => "NOTENOUGHROWS",
            '14' => "MTTIMEOUT",
            '15' => "MTCANTCONNECT",
            '16' => "ALLTARGETSUNAVAILABLE",
            '17' => "MTINTERNALEXCEPTION",
            '18' => "MTEXCEEDSCONNECTIONLIMIT",
            '19' => "MTREJECTEDDUETOFILTERRULES",
            '20' => "DUPLICATERECORD",
            '21' => "FIELDTOLONGTOSTOREDATABASE",
            '22' => "WARNINGPRESENTWITHOUTERROR",
            '23' => "MULTIPLEVERIFICATIONERROR",
            '24' => "DECOMPRESSIONERROR",
            '25' => "DATANOTFOUNDERROR",
            '26' => "AUTHENTICATIONFAIL",
            '27' => "VERSIONORSERVICENOTAVAILABLE",
            '28' => "INVALIDREQUEST",
            '29' => "INVALIDUSERUUIDTYPE",
            '30' => "HTTPRESPONDERROR",
            '31' => "FAILEDINTOCLASS",
            '32' => "TOKENISEMPTY",
            '33' => "TOKENISNULL",
            '34' => "INVALIDALGORITHMRESULT",
            '35' => "RATELIMITEXCEEDED",
            '36' => "NODATARETURNED",
            '37' => "SERVICENAMENOTAVAILABLE",
            '38' => "SERVICEVERSIONNOTAVAILABLE",
            '39' => "CAMELROUTESNOTAVAILABLE",
            '40' => "SERVICENAMENOTEMPTY",
            '41' => "SERVICEVERSIONNOTEMPTY",
            '42' => "APPLICATIONCODENOTREGISTERED",
            '43' => "REQUESTERIPNOTREGISTERED",
            '44' => "AGENCYCODENOTFOUND",
            '45' => "INVALIDUSERUUID",
            '46' => "HPMKMESSAGEHEADERNOTAVAILABLE",
            '47' => "HPMKMESSAGEPAYLOADNOTAVAILABLE",
            '48' => "AGENCYAPPAUTHCODENOTAVAILABLE",
            '49' => "AGENCYAPPAUTHKEYNOTAVAILABLE",
            '50' => "AGENCYCODENOTAVAILABLE",
            '51' => "APPLICATIONCODENOTAVAILABLE",
            '52' => "MESSAGESENTDATENOTAVAILABLE",
            '53' => "REQUESTUSERUUIDNOTAVAILABLE",
            '54' => "REQUESTUSERUUIDTYPENOTAVAILABLE",
            '55' => "REQUESTUSERUUIDTYPENOTREGISTERED",
            '56' => "REQUIREDMESSAGEPAYLOADEITHERNULLOREMPTY",
            '57' => "REQUESTRECEIVEDDATETIME",
            '58' => "RESPONSESENTDATETIME",
            '400' => "TOKENINVALID",
            '401' => "TOKENEXPIRED",
            '403' => "AUTHENTICATIONSERVERDOWN",
            '404' => "PAGENOTFOUND",
            '405' => "AUTHENTICATIONSERVERRETURNFALSE",
            '406' => "AUTHENTICATIONTOKENREQUIRED",
            '409' => "CONFLICT",
            '417' => "EXPECTATIONFAILED",
            '422' => "UNPROCESSABLEENTITY",
            '503' => "SERVICEUNAVAILABLE",
            '511' => "NETWORKAUTHENTICATIONREQUIRED",
            '500' => "APPLICATIONERROR"
        );
        return isset($refs[$code]) ? $refs[$code] : "error code $code is undefined ";
    }
}
